keys:
  - &users
    - &caleb 483A112B3567C4F0DF8974E1D776F5702D7E83AB
  - &hosts
    - &littleboy age1ftswaxmqv2f6rc8qzqnrl2sdzmanrwuf844feqq9f6m9yvunl9vs0qmszl
creation_rules:
  - path_regex: hosts/littleboy/secrets.yaml$
    key_groups:
      - age:
          - *littleboy
        pgp:
          - *caleb
  - path_regex: hosts/modules/secrets.yaml$
    key_groups:
      - age:
          - *littleboy
        pgp:
          - *caleb
  - path_regex: hosts/pi-certs/step-ca/secrets.yaml
    key_groups:
      - pgp:
          - *caleb

