{
  flake.modules.nixos.wireless =
    {
      lib,
      config,
      ...
    }:
    let
      cfg = config.networking.wireless;

      reportIfaces = config.facter.report.hardware.network_interface or [ ];
      dhcpIfaces = config.facter.detected.dhcp.interfaces or [ ];

      # add more as needed - only needed if if name is not prefixed with wl or subclass is not WLAN
      wirelessDrivers = [
        "iwlwifi"
      ];

      isWireless =
        iface:
        let
          drivers = (iface.drivers or [ ]) ++ (if iface ? driver then [ iface.driver ] else [ ]);
          unixNames = iface.unix_device_names or [ ];
          nameIsWireless = lib.any (n: lib.hasPrefix "wl" n) unixNames;
          driverIsWireless = lib.any (d: lib.elem d wirelessDrivers) drivers;
          subclassIsWlan = (iface.sub_class.name or "") == "WLAN";
        in
        nameIsWireless || driverIsWireless || subclassIsWlan;

      wirelessInterfaceNames = lib.unique (
        lib.concatMap (iface: lib.filter (n: lib.elem n dhcpIfaces) (iface.unix_device_names or [ ])) (
          lib.filter isWireless reportIfaces
        )
      );

      wirelessDhcpNetworks = lib.listToAttrs (
        lib.map (ifname: {
          name = "40-${ifname}";
          value = {
            inherit (config.systemd.network.networks."99-wireless-client-dhcp")
              dhcpV4Config
              ipv6AcceptRAConfig
              ;
          };
        }) wirelessInterfaceNames
      );
    in
    {
      sops.secrets.wireless = lib.mkIf cfg.enable {
        sopsFile = ../secrets/secrets.yaml;
        restartUnits = [ "wpa_supplicant.service" ];
        owner = "wpa_supplicant";
      };

      networking.wireless = {
        enable = lib.mkDefault true;
        userControlled = lib.mkDefault true;
        fallbackToWPA2 = lib.mkDefault false;
        allowAuxiliaryImperativeNetworks = lib.mkDefault false;
        secretsFile = config.sops.secrets.wireless.path;
        networks = {
          "Penguin Plaza".pskRaw = "ext:home_psk";
          "Nortfam6".pskRaw = "ext:fam_psk";
          "TAMU_WiFi" = {
            authProtocols = [ "WPA-EAP" ];
            priority = 10;
            auth = ''
              eap=PEAP
              identity="chnorton"
              password=ext:tamu_psk
            '';
          };
          "eduroam" = {
            authProtocols = [ "WPA-EAP" ];
            auth = ''
              eap=PEAP
              identity="chnorton@tamu.edu"
              password=ext:tamu_psk
            '';
          };
          "Caleb's iPhone".pskRaw = "ext:hotspot_psk";
          "Reveille Ranch Resident".pskRaw = "ext:rev_ranch_psk";
          "SpectrumSetup-7E".pskRaw = "ext:gg_psk";
        };
      };

      # set wifi card dynamic routes to lower priority than ethernet - this is done by the 99-wireless-client-dhcp.network
      # but systemd network does not merge multiple matching network files, it takes the first match and ignores the rest
      # so we have to augment the one generated by nixos modules
      # https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/network-interfaces-systemd.nix
      # FIXME: how does this interact with interfaces with DHCP disabled?
      systemd.network.networks = lib.mkIf config.networking.useDHCP wirelessDhcpNetworks;
    };
}
