{
  configurations.nixos.chnorton-fw = {
    home-manager.users.caleb =
      {
        lib,
        pkgs,
        osConfig,
        ...
      }:
      {
        home.packages = builtins.attrValues {
          inherit (pkgs)
            wpa_supplicant_gui
            manga-dl
            ;
          inherit (pkgs.kdePackages)
            okular
            ;
          # inherit (pkgs.python3Packages)
          #   meshtastic
          #   ;
        };

        xdg.mimeApps = {
          enable = true;
          defaultApplications = {
            "application/pdf" = "org.kde.okular.desktop";
          };
        };

        # amd gpu
        programs.btop.package = pkgs.btop-rocm;

        programs.spotify.enable = true;
        programs.ghostty.enable = true;
        programs.firefox.enable = true;
        programs.trilium.enable = true;
        programs.vesktop.enable = true;
        # programs.bitwarden.enable = true;
        # programs.libreoffice.enable = true;
        # programs.newsflash.enable = true;
        programs.onlyoffice.enable = true;
        # programs.prismlauncher.enable = true;

        # battery is set to charge to 80% max
        # sudo framework_tool --charge-limit
        programs.waybar.settings.mainBar.battery.full-at = 80;

        # TODO: move to separate module
        services.syncthing = {
          enable = true;
          tray.enable = lib.mkDefault true;
          # generated by running `nix-shell -p syncthing --run syncthing`
          # and grabbing the generated cert and key files from ~/.local/state/syncthing
          cert = "${./syncthing-cert.pem}";
          key = osConfig.sops.secrets.syncthing_key.path;
        };

        programs.radicle = {
          publicKey = ./radicle.pub;
          privateKeyFile = osConfig.sops.secrets.radicle_key.path;
        };

        # TODO: mode the shared module?
        programs.ssh = {
          enable = true;
          enableDefaultConfig = false;
          includes = [ "config.custom" ];
          settings = {
            "*" = {
              # add keys to agent but only forward to trusted servers
              ForwardAgent = false;
              AddKeysToAgent = "yes";
              Compression = false;
              ServerAliveInterval = 0;
              ServerAliveCountMax = 3;
              HashKnownHosts = false;
              UserKnownHostsFile = "~/.ssh/known_hosts";
              ControlMaster = "auto";
              ControlPath = "~/.ssh/master-%r@%n:%p";
              ControlPersist = "no";
            };
            "github.com" = {
              User = "git";
              ControlMaster = "no";
              ControlPath = "none";
            };
            "kvs" = {
              HostName = "ecewkgsw05201.engr.tamu.edu";
              User = "chnorton";
              ForwardAgent = true;
            };
            "wyse-*.penguin" = {
              User = "root";
            };
            "olympus" = {
              HostName = "olympus.ece.tamu.edu";
              User = "chnorton";
              ForwardAgent = true;
            };
            "ieee-tamu" = {
              HostName = "ieee-tamu.engr.tamu.edu";
              User = "root";
              SetEnv = {
                TERM = "xterm-256color";
              };
            };
            "ieee-tamu-*" = {
              User = "root";
              ProxyJump = "ieee-tamu";
            };
          };
        };

        services.ollama = {
          enable = true;
          package = pkgs.ollama-vulkan;
        };

        # try out hunk: https://github.com/modem-dev/hunk
        programs.jujutsu.settings.ui = {
          pager = [
            (lib.getExe pkgs.hunk)
            "pager"
          ];
          diff-formatter = ":git";
        };
        # TODO: use tomlFormat
        xdg.configFile."hunk/config.toml" = {
          text = ''
            vcs = "jj"
          '';
        };
      };
  };

  persistence.wrappers.homeManager = [
    {
      name = "trilium";
      packageName = "trilium-next-desktop";
    }
    {
      name = "bitwarden";
      packageName = "bitwarden-desktop";
    }
    "newsflash"
    {
      name = "libreoffice";
      packageName = "libreoffice-fresh";
    }
  ];

  persistence.programs.homeManager = {
    vesktop = {
      directories = [ ".config/vesktop" ];
    };
    trilium = {
      directories = [ ".local/share/trilium-data" ];
    };
    bitwarden = {
      directories = [ ".config/Bitwarden" ];
    };
    newsflash = {
      directories = [
        ".config/news-flash"
        ".local/share/news-flash"
      ];
    };
    prismlauncher = {
      directories = [
        ".local/share/PrismLauncher"
      ];
    };
    libreoffice = {
      directories = [
        ".config/libreoffice"
        # ".local/share/libreoffice"
      ];
    };
    google-chrome = {
      directories = [
        ".config/google-chrome"
      ];
    };
    # issue - ollama does not seem to create its ssh keys on first run if the .ollama directory already exists
    ollama = {
      namespace = "services";
      directories = [ ".ollama" ];
    };
  };
}
