{
  configurations.nixos.chnorton-fw = {
    home-manager.users.caleb =
      {
        lib,
        pkgs,
        osConfig,
        config,
        ...
      }:
      {
        home.packages = builtins.attrValues {
          inherit (pkgs)
            wpa_supplicant_gui
            manga-dl
            ;
          # inherit (pkgs.python3Packages)
          #   meshtastic
          #   ;
        };

        xdg.mimeApps = {
          enable = true;
          defaultApplications = {
            "application/pdf" = lib.mkIf config.programs.firefox.enable "firefox.desktop";
          };
        };

        # amd gpu
        programs.btop.package = pkgs.btop-rocm;

        programs.spotify.enable = true;
        programs.ghostty.enable = true;
        programs.firefox.enable = true;
        programs.trilium.enable = true;
        programs.vesktop.enable = true;
        programs.onlyoffice.enable = true;
        programs.obs-studio.enable = true;
        programs.kicad.enable = true;
        programs.heroic.enable = false;
        programs.element-desktop.enable = false;

        # battery is set to charge to 80% max
        # sudo framework_tool --charge-limit
        programs.waybar.settings.mainBar.battery.full-at = 80;

        # auto brightness via ambient light sensor (framework als, iio:device0)
        services.wluma = {
          enable = false; # didnt seem to work very well - would randomly dim the screen - maybe bad training?
          settings = {
            als.iio = {
              path = "/sys/bus/iio/devices";
              thresholds = {
                "0" = "night";
                "20" = "dark";
                "80" = "dim";
                "250" = "normal";
                "500" = "bright";
                "800" = "outdoors";
              };
            };
            output.backlight = [
              {
                name = "eDP-1";
                path = "/sys/class/backlight/amdgpu_bl1";
                capturer = "wayland";
              }
            ];
            keyboard = [
              {
                name = "keyboard-framework";
                path = "/sys/class/leds/framework_laptop::kbd_backlight";
              }
            ];
          };
        };

        # TODO: move to separate module
        services.syncthing = {
          enable = true;
          tray.enable = lib.mkDefault true;
          # generated by running `nix-shell -p syncthing --run syncthing`
          # and grabbing the generated cert and key files from ~/.local/state/syncthing
          cert = "${./syncthing-cert.pem}";
          key = osConfig.sops.secrets.syncthing_key.path;
        };

        programs.radicle = {
          enable = false;
          publicKey = ./radicle.pub;
          privateKeyFile = osConfig.sops.secrets.radicle_key.path;
        };

        # TODO: mode the shared module?
        programs.ssh = {
          enable = true;
          enableDefaultConfig = false;
          includes = [ "config.custom" ];
          settings = {
            "*" = {
              # add keys to agent but only forward to trusted servers
              ForwardAgent = false;
              AddKeysToAgent = "yes";
              Compression = false;
              ServerAliveInterval = 0;
              ServerAliveCountMax = 3;
              HashKnownHosts = false;
              UserKnownHostsFile = "~/.ssh/known_hosts";
              ControlMaster = "auto";
              ControlPath = "~/.ssh/master-%r@%n:%p";
              ControlPersist = "no";
            };
            "github.com" = {
              User = "git";
              ControlMaster = "no";
              ControlPath = "none";
            };
            "kvs ecewkgsw05201.engr.tamu.edu" = {
              HostName = "ecewkgsw05201.engr.tamu.edu";
              User = "chnorton";
              ForwardAgent = true;
              ControlPath = "~/.ssh/master-%r@%h:%p"; # use resolved hostname - make global?
            };
            "wyse-*.penguin" = {
              User = "root";
            };
            "switch.penguin" = {
              # old switch only offers ssh-rsa (SHA-1) host keys
              HostKeyAlgorithms = "+ssh-rsa";
              PubkeyAcceptedAlgorithms = "+ssh-rsa";
              SetEnv = {
                TERM = "xterm-256color";
              };
            };
            "olympus olympus.ece.tamu.edu" = {
              HostName = "olympus.ece.tamu.edu";
              User = "chnorton";
              ForwardAgent = true;
            };
            "ieee-tamu ieee-tamu.engr.tamu.edu" = {
              HostName = "ieee-tamu.engr.tamu.edu";
              User = "root";
              SetEnv = {
                TERM = "xterm-256color";
              };
            };
            "ieee-tamu-*" = {
              User = "root";
              ProxyJump = "ieee-tamu";
              SetEnv = {
                TERM = "xterm-256color";
              };
            };
          };
        };

        services.ollama = {
          # enable = true;
          package = pkgs.ollama-vulkan;
        };

        programs.opencode.context = ''
          ## NixOS Environment

          This is a NixOS system. Tools like `python3`, `node`, `pip`, `npm`, `go`, `rustc`, etc. are NOT globally installed and will NOT be found on PATH.

          **Before running or writing code that depends on any tool, check if it exists first.** If a tool is missing:

          1. **Preferred**: Use `nix-shell -p <pkg>` for one-off commands:
             - `nix-shell -p python3 --run "python script.py"`
             - `nix-shell -p nodejs --run "npm test"`
             - `nix-shell -p go --run "go build ./..."`

          2. **For repeated use**: Check if the project already has a `shell.nix` or `flake.nix` devShell, then use `nix develop` or `nix-shell`.

          3. **If no shell exists**: Create a `shell.nix` with the needed packages:
             ```nix
             { pkgs ? import <nixpkgs> {} }:
             pkgs.mkShell {
               buildInputs = with pkgs; [ python3 nodejs ];
             }
             ```
             Then run `nix-shell` to enter the environment, or `nix-shell --run "<command>"`.

          4. **direnv**: Many projects use direnv with nix-direnv to automatically load dev shells. The opencode-direnv plugin automatically loads project-specific dev environments into the agent's shell tool calls — tools from the project's nix shell should already be available on PATH when running commands.

          **Important**: Never assume tools like `python` or `python3` exist. Always use `nix-shell -p <pkg>` or the project's nix shell when running anything that requires external tools.
        '';
      };
  };

  persistence.wrappers.homeManager = [
    {
      name = "trilium";
      packageName = "trilium-next-desktop";
    }
    {
      name = "bitwarden";
      packageName = "bitwarden-desktop";
    }
    "newsflash"
  ];

  persistence.programs.homeManager = {
    vesktop = {
      directories = [ ".config/vesktop" ];
    };
    trilium = {
      directories = [ ".local/share/trilium-data" ];
    };
    bitwarden = {
      directories = [ ".config/Bitwarden" ];
    };
    newsflash = {
      directories = [
        ".config/news-flash"
        ".local/share/news-flash"
      ];
    };
    prismlauncher = {
      directories = [
        ".local/share/PrismLauncher"
      ];
    };
    google-chrome = {
      directories = [
        ".config/google-chrome"
      ];
    };
    # issue - ollama does not seem to create its ssh keys on first run if the .ollama directory already exists
    ollama = {
      namespace = "services";
      directories = [ ".ollama" ];
    };
    # learned brightness preferences per ALS profile
    wluma = {
      namespace = "services";
      directories = [ ".local/share/wluma" ];
    };
  };
}
