name: "Build and populate cache"
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true
    - name: Build cachix
      run: nix run nixpkgs#nix-fast-build -- --skip-cached --no-nom --no-link --cachix-cache gigamonster256 --flake ".#ci.$(nix eval --raw --impure --expr builtins.currentSystem).cachix"
      env:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build artifacts
      run: nix run nixpkgs#nix-fast-build -- --skip-cached --no-nom --flake ".#ci.$(nix eval --raw --impure --expr builtins.currentSystem).artifacts"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        retention-days: 7
        overwrite: true
        path: ./result-*
        name: artifacts-${{ runner.os }}
        
