name: "Build and populate cache"
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    # TODO: see about having nix-fast-build do the uploading
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: gigamonster256
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build and cache
      run: nix run nixpkgs#nix-fast-build -- --skip-cached --no-nom --no-link --flake ".#ci.$(nix eval --raw --impure --expr builtins.currentSystem)"
