name: "Build and populate cache"
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        build: [artifacts, cachix]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          # fix for https://github.com/nix-community/nix-eval-jobs/issues/140
          # nix-eval-jobs does not respect flake's nixConfig when checking to see if a 
          # derivation is already cached
          # accept-flake-config = true
          extra-substituters = https://gigamonster256.cachix.org
          extra-trusted-public-keys = gigamonster256.cachix.org-1:ySCUrOkKSOPm+UTipqGtGH63zybcjxr/Wx0UabASvRc=
    - name: Setup cachix
      if: ${{ matrix.build == 'cachix' }}
      uses: cachix/cachix-action@v16
      with:
        name: gigamonster256
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix run --inputs-from . nixpkgs#nix-fast-build -- --skip-cached --no-nom --flake ".#ci.$(nix eval --raw --impure --expr builtins.currentSystem).${{ matrix.build }}"
    - name: Upload artifacts
      if: ${{ matrix.build == 'artifacts' }}
      uses: actions/upload-artifact@v4.6.2
      with:
        retention-days: 7
        if-no-files-found: ignore
        path: ./result-*
        name: artifacts-${{ matrix.os }}
