---
name: "Update flakes"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v22
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
            automerge
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PULL_REQUEST: "${{ steps.update.outputs.pull-request-number }}"
            
