---
name: "Update flakes"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * SUN,WED"
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
            automerge
          branch: flake-update

